# Generated by Django 5.0.3 on 2024-03-24 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes_app', '0001_initial'),
        ('pontos_turisticos_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='atracoes',
            field=models.ManyToManyField(to='atracoes_app.atracao'),
        ),
    ]
