# Generated by Django 5.0.3 on 2024-03-24 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao_app', '0002_remove_avaliacao_comentario'),
        ('comentario_app', '0001_initial'),
        ('pontos_turisticos_app', '0002_pontoturistico_atracoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='avaliacoes',
            field=models.ManyToManyField(to='avaliacao_app.avaliacao'),
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='comentarios',
            field=models.ManyToManyField(to='comentario_app.comentario'),
        ),
    ]
