# Generated by Django 5.0.3 on 2024-03-24 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endereco_app', '0001_initial'),
        ('pontos_turisticos_app', '0003_pontoturistico_avaliacoes_pontoturistico_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='endereco',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='endereco_app.endereco'),
            preserve_default=False,
        ),
    ]
