# Generated by Django 5.0.3 on 2024-03-24 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='comentario',
        ),
    ]
